spring:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:warehouse
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 300000
      maximum-pool-size: 7
      minimum-idle: 7
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
    open-in-view: false

app:
  jwt:
    secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expiration-milliseconds: 3600000
    authorities.key: roles
    header.string: Authorization
    token.prefix: Bearer
